name: continuous integration & continuous deployment to GitHub Pages
on:
  push:
    branches:
      - deployed
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: check out branch
        uses: actions/checkout@v2
      - name: authorize GitHub action
        uses: oleksiyrudenko/gha-git-credentials@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: set up node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: install dependencies
        run: npm install
      - name: check code quality (prettier, lint and typescript)
        run: npm run check
      - name: build
        run: npm run build
      - name: deploy
        run: npm run deploy
